/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package corona

import kotlin.test.Test
import kotlin.test.assertFalse

class PersonTest {
    @Test fun testAppHasAGreeting() {
        val michaelState: InfectionState  = InfectionState(false, false)
        val classUnderTest = Person("Michael", 45, michaelState)
        assertFalse(classUnderTest.infectionState.infected, "michael should be not infected")
    }
}
